### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by Trinsec** [meld-cp/obsidian-calc#6]
Heya, I was wondering if this plugin's still relevant for Obsidian v0.13.30? I can't seem to get it to work, the Meld Calc: Evaluate command doesn't exist in the command palette whenever I enable this and the hotkey won't react.

**Comment by erex** [comment]
I'm running 0.14.2 and the `Evaluate` command appears on the command palette but only after you have highlighted an expression to be evaluated, such as the expression shown in the read.me

PI * 4cm ^ 2 =
